
DATA_PATH = "data/"
DATA_MEMBERS_FILENAME = "data_members"
DATA_THEME_FILENAME = "data_theme"

COLLECTING_TOKENS, COLLECTING_SUGGESTIONS, REPLYING, \
    FINISHED_COLLECTING_TOKENS, FINISHED_COLLECTING_SUGGESTIONS = range(5)


